<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Receipt #{{ $entry->id }}</title>
    <style>
        body { font-family: DejaVu Sans, Helvetica, Arial, sans-serif; color: #222; }
        .header { text-align: center; margin-bottom: 20px; }
        .box { border: 1px solid #eee; padding: 12px; border-radius: 6px; }
        .row { display:flex; justify-content:space-between; margin-bottom:8px; }
        .muted { color:#666; font-size:12px; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Transaction Receipt</h2>
        <div class="muted">{{ $entry->entry_date?->format('Y-m-d') }}</div>
    </div>

    <div class="box">
        <div class="row"><div><strong>Transaction ID:</strong></div><div>#{{ $entry->id }}</div></div>
        <div class="row"><div><strong>Type:</strong></div><div>{{ ucfirst($entry->entry_type) }}</div></div>
        <div class="row"><div><strong>Amount:</strong></div><div>₹{{ number_format($entry->amount,2) }}</div></div>
        <div class="row"><div><strong>Category:</strong></div><div>{{ $entry->category }}</div></div>
        <div class="row"><div><strong>Payment Method:</strong></div><div>{{ $entry->payment_mode }}</div></div>
        <div class="row"><div><strong>Reference:</strong></div><div>{{ $entry->reference_number }}</div></div>
        <div class="row"><div><strong>Description:</strong></div><div>{{ $entry->description }}</div></div>
    </div>

    <div style="margin-top:20px;font-size:12px;color:#666;">Generated by TransportSDR</div>
</body>
</html>
